# Generated by Django 5.2.8 on 2025-11-25 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
