# Generated by Django 5.2.8 on 2026-03-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='ChatConversation',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
