# Generated by Django 6.0.6 on 2026-06-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_order_city_alter_order_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('dakar', 'Dakar (livraison rapide)'), ('regions', 'Autres régions')], default='dakar', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Paiement à la livraison'), ('wave', 'Wave'), ('om', 'Orange Money')], default='cod', max_length=10),
        ),
    ]
